### ISSUE TITLE
Link to track, not album

### ISSUE THREAD

**Issue by joksas** [Podcastindex-org/top100_music#3]
Currently, for each track, there exists a link of the form `https://podcastindex.org/podcast/{{ podcastID }}`.

I think `https://podcastindex.org/podcast/{{ podcastID }}?episode={{ episodeID }}` would make more sense.

**Comment by stevencrader** [comment]
Agree

https://podcastindex.social/@dave/111001072511848078

**Comment by daveajones** [comment]
Yep it’s on the to-do list.

**Comment by daveajones** [comment]
Done!

https://stats.podcastindex.org/v4vmusic.html
